/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardSensorsRouteImport } from './routes/dashboard/sensors'
import { Route as DashboardRobotsRouteImport } from './routes/dashboard/robots'
import { Route as DashboardMapsRouteImport } from './routes/dashboard/maps'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSensorsRoute = DashboardSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRobotsRoute = DashboardRobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMapsRoute = DashboardMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/robots': typeof DashboardRobotsRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/robots': typeof DashboardRobotsRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/robots': typeof DashboardRobotsRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/maps'
    | '/dashboard/robots'
    | '/dashboard/sensors'
    | '/dashboard/tasks'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/maps'
    | '/dashboard/robots'
    | '/dashboard/sensors'
    | '/dashboard/tasks'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/maps'
    | '/dashboard/robots'
    | '/dashboard/sensors'
    | '/dashboard/tasks'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sensors': {
      id: '/dashboard/sensors'
      path: '/sensors'
      fullPath: '/dashboard/sensors'
      preLoaderRoute: typeof DashboardSensorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/robots': {
      id: '/dashboard/robots'
      path: '/robots'
      fullPath: '/dashboard/robots'
      preLoaderRoute: typeof DashboardRobotsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/maps': {
      id: '/dashboard/maps'
      path: '/maps'
      fullPath: '/dashboard/maps'
      preLoaderRoute: typeof DashboardMapsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardMapsRoute: typeof DashboardMapsRoute
  DashboardRobotsRoute: typeof DashboardRobotsRoute
  DashboardSensorsRoute: typeof DashboardSensorsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMapsRoute: DashboardMapsRoute,
  DashboardRobotsRoute: DashboardRobotsRoute,
  DashboardSensorsRoute: DashboardSensorsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
